name: nightly-run
on:
  schedule:
    - cron: '30 21 * * *'    # 21:30 UTC daily
  workflow_dispatch:         # allow manual runs too
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run nightly script
        run: |
          . .venv/bin/activate
          python scripts/main.py